### ISSUE TITLE
Action is not executable

### ISSUE THREAD

**Issue by jromero** [dfreilich/pack-action#6]
In [buildpacks/pack](https://github.com/buildpacks/pack) which uses this action, recently received the following error:

`standard_init_linux.go:219: exec user process caused: no such file or directory`

After some investigation, I was able to determine that:

*  It was due to `entrypoint.sh` not being executable.
    *  Cause: the base image `buildpacksio/pack` is pointing to a mutable tag and the latest version no longer includes `/bin/sh`.
        * Cause: `/bin/sh` is no longer present due to now being build by the paketo tiny builder

### Proposal

1. Tagged versions of the action should be using an immutable tag or image sha as the base.
1. No `entrypoint.sh` should be necessary if we can solve not needing to pass auth.
1. If `entrypoint.sh` is necessary, something like busybox can be used to augment the base build.

**Comment by dfreilich** [comment]
Sorry I didn't see this earlier! I didn't get notifications about the issues/PR for this. I'll test it and merge it in ASAP. Thanks for the help @jromero
